# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- devops/doghappy

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
steps:
  - script: |
      dotnet build HappyDog.WebUI --configuration $(buildConfiguration)
      displayName: 'dotnet build HappyDog.WebUI $(buildConfiguration)'
      docker build -f HappyDog.WebUI/Dockerfile -t doghappy/doghappy .
      docker login -u $(DockerId) -p $(DockerPassword)
      docker push doghappy/doghappy